countries_and_currency_codes = {
    'United Arab Emirates': 'AED',
    'Afghanistan': 'AFN',
    'Albania': 'ALL',
    'Armenia': 'AMD',
    'Netherlands Antilles': 'ANG',
    'Angola': 'AOA',
    'Argentina': 'ARS',
    'Australia': 'AUD',
    'Aruba': 'AWG',
    'Azerbaijan': 'AZN',
    'Bosnia and Herzegovina': 'BAM',
    'Barbados': 'BBD',
    'Bangladesh': 'BDT',
    'Bulgaria': 'BGN',
    'Bahrain': 'BHD',
    'Burundi': 'BIF',
    'Bermuda': 'BMD',
    'Brunei': 'BND',
    'Bolivia': 'BOB',
    'Brazil': 'BRL',
    'Bahamas': 'BSD',
    'Bitcoin': 'BTC',
    'Bhutan': 'BTN',
    'Botswana': 'BWP',
    'Belarus': 'BYN',
    'Belarus (pre-2016)': 'BYR',
    'Belize': 'BZD',
    'Canada': 'CAD',
    'Democratic Republic of the Congo': 'CDF',
    'Switzerland': 'CHF',
    'Chile (Unidad de Fomento)': 'CLF',
    'Chile': 'CLP',
    'China': 'CNY',
    'Colombia': 'COP',
    'Costa Rica': 'CRC',
    'Cuba (Convertible Peso)': 'CUC',
    'Cuba': 'CUP',
    'Cape Verde': 'CVE',
    'Czech Republic': 'CZK',
    'Djibouti': 'DJF',
    'Denmark': 'DKK',
    'Dominican Republic': 'DOP',
    'Algeria': 'DZD',
    'Egypt': 'EGP',
    'Eritrea': 'ERN',
    'Ethiopia': 'ETB',
    'Eurozone': 'EUR',
    'Fiji': 'FJD',
    'Falkland Islands': 'FKP',
    'United Kingdom': 'GBP',
    'Georgia': 'GEL',
    'Guernsey': 'GGP',
    'Ghana': 'GHS',
    'Gibraltar': 'GIP',
    'Gambia': 'GMD',
    'Guinea': 'GNF',
    'Guatemala': 'GTQ',
    'Guyana': 'GYD',
    'Hong Kong': 'HKD',
    'Honduras': 'HNL',
    'Croatia': 'HRK',
    'Haiti': 'HTG',
    'Hungary': 'HUF',
    'Indonesia': 'IDR',
    'Israel': 'ILS',
    'Isle of Man': 'IMP',
    'India': 'INR',
    'Iraq': 'IQD',
    'Iran': 'IRR',
    'Iceland': 'ISK',
    'Jersey': 'JEP',
    'Jamaica': 'JMD',
    'Jordan': 'JOD',
    'Japan': 'JPY',
    'Kenya': 'KES',
    'Kyrgyzstan': 'KGS',
    'Cambodia': 'KHR',
    'Comoros': 'KMF',
    'North Korea': 'KPW',
    'South Korea': 'KRW',
    'Kuwait': 'KWD',
    'Cayman Islands': 'KYD',
    'Kazakhstan': 'KZT',
    'Laos': 'LAK',
    'Lebanon': 'LBP',
    'Sri Lanka': 'LKR',
    'Liberia': 'LRD',
    'Lesotho': 'LSL',
    'Lithuania': 'LTL',
    'Latvia': 'LVL',
    'Libya': 'LYD',
    'Morocco': 'MAD',
    'Moldova': 'MDL',
    'Madagascar': 'MGA',
    'North Macedonia': 'MKD',
    'Myanmar': 'MMK',
    'Mongolia': 'MNT',
    'Macau': 'MOP',
    'Mauritania': 'MRU',
    'Mauritius': 'MUR',
    'Maldives': 'MVR',
    'Malawi': 'MWK',
    'Mexico': 'MXN',
    'Malaysia': 'MYR',
    'Mozambique': 'MZN',
    'Namibia': 'NAD',
    'Nigeria': 'NGN',
    'Nicaragua': 'NIO',
    'Norway': 'NOK',
    'Nepal': 'NPR',
    'New Zealand': 'NZD',
    'Oman': 'OMR',
    'Panama': 'PAB',
    'Peru': 'PEN',
    'Papua New Guinea': 'PGK',
    'Philippines': 'PHP',
    'Pakistan': 'PKR',
    'Poland': 'PLN',
    'Paraguay': 'PYG',
    'Qatar': 'QAR',
    'Romania': 'RON',
    'Serbia': 'RSD',
    'Russia': 'RUB',
    'Rwanda': 'RWF',
    'Saudi Arabia': 'SAR',
    'Solomon Islands': 'SBD',
    'Seychelles': 'SCR',
    'Sudan': 'SDG',
    'Sweden': 'SEK',
    'Singapore': 'SGD',
    'Saint Helena': 'SHP',
    'Sierra Leone': 'SLE',
    'Sierra Leone (pre-2016)': 'SLL',
    'Somalia': 'SOS',
    'Suriname': 'SRD',
    'São Tomé and Príncipe': 'STD',
    'Syria': 'SYP',
    'Eswatini': 'SZL',
    'Thailand': 'THB',
    'Tajikistan': 'TJS',
    'Turkmenistan': 'TMT',
    'Tunisia': 'TND',
    'Tonga': 'TOP',
    'Turkey': 'TRY',
    'Trinidad and Tobago': 'TTD',
    'Taiwan': 'TWD',
    'Tanzania': 'TZS',
    'Ukraine': 'UAH',
    'Uganda': 'UGX',
    'United States': 'USD',
    'Uruguay': 'UYU',
    'Uzbekistan': 'UZS',
    'Venezuela (pre-2018)': 'VEF',
    'Venezuela': 'VES',
    'Vietnam': 'VND',
    'Vanuatu': 'VUV',
    'Samoa': 'WST',
    'Central African CFA franc': 'XAF',
    'Silver (one troy ounce)': 'XAG',
    'Gold (one troy ounce)': 'XAU',
    'Eastern Caribbean Dollar': 'XCD',
    'Special Drawing Rights': 'XDR',
    'West African CFA franc': 'XOF',
    'French Pacific Franc': 'XPF',
    'Yemen': 'YER',
    'South Africa': 'ZAR',
    'Zambia (pre-2013)': 'ZMK',
    'Zambia': 'ZMW',
    'Zimbabwe (pre-2009)': 'ZWL',
}